{{--
     GENERATED FILE -- do not hand-edit. Regenerate with:
       npm run generate:pwa-splash (scripts/generate-pwa-splash.mjs)
     Included from layouts/app.blade.php's <head>.
--}}
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-375-667-2x-light.png" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-375-667-2x-dark.png" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-375-812-3x-light.png" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-375-812-3x-dark.png" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-414-896-2x-light.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: light)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-414-896-2x-dark.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait) and (prefers-color-scheme: dark)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-414-896-3x-light.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-414-896-3x-dark.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-390-844-3x-light.png" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-390-844-3x-dark.png" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-428-926-3x-light.png" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-428-926-3x-dark.png" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-393-852-3x-light.png" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-393-852-3x-dark.png" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-430-932-3x-light.png" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-430-932-3x-dark.png" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-402-874-3x-light.png" media="(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-402-874-3x-dark.png" media="(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-440-956-3x-light.png" media="(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-440-956-3x-dark.png" media="(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-420-912-3x-light.png" media="(device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: light)">
<link rel="apple-touch-startup-image" href="/icons/splash/apple-splash-420-912-3x-dark.png" media="(device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait) and (prefers-color-scheme: dark)">
