dist: bionic

language: php

php:
  - '7.3'

addons:
  mariadb: '10.4'

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE USER travis@localhost;'
  - sudo mysql -e 'CREATE DATABASE testing;'
  - sudo mysql -e 'GRANT ALL ON *.* to travis@localhost;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit